### ISSUE TITLE
Error probably relate to package name change

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/strapi-plugin-ckeditor#1]
```
[2022-09-28 09:58:28.510] error: Could not find Custom Field: plugin::@ckeditor/strapi-plugin-ckeditor.CKEditor
Error: Could not find Custom Field: plugin::@ckeditor/strapi-plugin-ckeditor.CKEditor
    at Object.get (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/strapi/lib/core/registries/custom-fields.js:16:15)
    at /Users/p/Workspace/strapi/strapi/node_modules/@strapi/plugin-content-type-builder/server/services/schema-builder/utils/convert-custom-field-type.js:13:65
    at Array.forEach (<anonymous>)
    at convertCustomFieldType (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/plugin-content-type-builder/server/services/schema-builder/utils/convert-custom-field-type.js:9:29)
    at Object.createContentType (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/plugin-content-type-builder/server/services/schema-builder/content-type-builder.js:82:7)
    at Object.createContentType (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/plugin-content-type-builder/server/services/content-types.js:87:34)
    at Object.createContentType (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/plugin-content-type-builder/server/controllers/content-types.js:62:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async returnBodyMiddleware (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/p/Workspace/strapi/strapi/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
```

Most likely related to the package name change (from `strapi-plugin-ckeditor` to `@ckeditor/strapi-plugin-ckeditor`). Probably I should've changed it somewhere in the plugin code too.

This appears on the console when adding a CKEditor field to a type. So the custom field is actually shown and works, but upon saving this, this is logged.

**Comment by darokviana** [comment]
How did you solve it?
